### ISSUE TITLE
非法修改网址过后出现的无限302重定向错误

### ISSUE THREAD

**Issue by TheSnowfield** [VOID001/NEUOJ#1]
在主页oj.neu.edu.cn中间的"Trainings"只有两个题库。随意点一个进去。跳转到 oj.neu.edu.cn/training/2 (我点的是第二个题库) 
呐现在, 如果是把 oj.neu.edu.cn/training/2 的2改成题库列表中不存在的值( num >2 ) 则可能会造成**无限302重定向错误**： 
 "该网页无法正常运作 oj.neu.edu.cn 将您重定向的次数过多。尝试清除Cookie.ERR_TOO_MANY_REDIRECTS"
还有一定几率会爆出当前用户头像和主页logo。

**Comment by onionwyl** [comment]
Fixed
